name: 'Docker Build and Run Setup'
description: 'Build Docker container and define DOCKER_RUN variable'

inputs:
  cache_dir:
    description: 'Path to the ccache directory'
    required: true

runs:
  using: "composite"
  steps:
    - name: Build Docker container
      shell: bash
      run: docker build -f build/Dockerfile . --tag epsilon-builder

    - name: Define DOCKER_RUN environment variable
      shell: bash
      run: |
        echo "DOCKER_RUN=docker run -i --user=$(id -u):$(id -g) --env CCACHE_DIR=/cache --mount type=bind,source=${{ inputs.cache_dir }},target=/cache --mount type=bind,source=.,target=/epsilon epsilon-builder:latest sh -c" >> $GITHUB_ENV
