APP_NAME = rpn
APP_ICON_PATH = src/icon.png

OUTPUT_PATH = output/

SOURCES = $(addprefix src/,\
  converter.cpp \
  input_field.cpp \
  main.cpp \
  store.cpp \
  view.cpp \
)

include build/cpp_external_app.mak
