APP_NAME = voord
APP_ICON_PATH = src/icon.png

OUTPUT_PATH = output/

SOURCES = $(addprefix src/,\
  alien.cpp \
  life.cpp \
  main.cpp \
  rocket.cpp \
  spaceship.cpp \
  score.cpp \
)

include build/cpp_external_app.mak
